CREATE TABLE IF NOT EXISTS public.fragen_level_zwei (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text TEXT NOT NULL,
  riasec_type CHAR(1) NOT NULL CHECK (riasec_type IN ('R', 'I', 'A', 'S', 'E', 'C'))
);
